import Head from 'next/head';
import Header from '../components/Header';
import MainContent from '../components/MainContent';
import styled from 'styled-components';

const Main = styled.main`
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  height: 100vh;
`;

export default function Home() {
  return (
    <Main>
      <Head>
        <title>HUBusca</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <MainContent />
    </Main>
  );
}
